name: Build and Release EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write   # needed for release creation and asset upload
  actions: write

env:
  EXE_REPO: DaSonOfPoseidon/exeFiles

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pyinstaller

      - id: extract_version
        shell: pwsh
        run: |
          $text = Get-Content -Raw -Encoding UTF8 ASSigner.py
          if ($text -match '(?m)^\s*__version__\s*=\s*["'']([^"'']+)["'']') {
            Write-Output "VERSION=$($matches[1])" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } else {
            throw "Version not found in ASSigner.py"
          }

      - name: Build executable
        run: pyinstaller ASSigner.spec

      - name: Create and push tag
        shell: bash
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          TAG="v${{ env.VERSION }}"
          if ! git rev-parse "$TAG" >/dev/null 2>&1; then
            git tag -a "$TAG" -m "Release version $TAG"
            git push origin "$TAG"
          else
            echo "Tag $TAG already exists"
          fi

      - name: Create or update GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: Automated release of ASSigner.exe version v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}   # add this line to specify which release
          files: dist/ASSigner.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger exeFiles update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ env.EXE_REPO }}
          event-type: exe_update
          client-payload: |
            {
              "exe_name": "ASSigner.exe",
              "version": "${{ env.VERSION }}",
              "release_repo": "JobAssignment"
            }
